# ====
# Step 1/3: maven-builder
# ====
ARG RHBK_IMAGE_VERSION=26.2-4
# -----------------------------------------
FROM registry.redhat.io/ubi9/openjdk-17:1.22-1.1745840591 AS maven-builder

ARG MAVEN_URL
ARG MAVEN_SETTINGS
ARG MAVEN_PROFILES

# Remember! This image (ubi9/openjdk-17) has the working directory: WORKDIR "/home/default"
#
COPY 00-download-libs.sh .
COPY pom.xml .
#COPY src ./src
#
RUN MAVEN_URL="${MAVEN_URL}" \
    MAVEN_SETTINGS="${MAVEN_SETTINGS}" \
    MAVEN_PROFILES="${MAVEN_PROFILES}" \
    ./00-download-libs.sh
#
RUN ls -l

# ====
# Step 2/3: builder-keycloak-image
# ====
FROM registry.redhat.io/rhbk/keycloak-rhel9:${RHBK_IMAGE_VERSION} AS builder-keycloak-image

USER root
#
COPY --from=maven-builder /home/default/target/libs/*.jar /opt/keycloak/providers/

RUN chown keycloak:keycloak /opt/keycloak/providers/*.jar && chmod 644 /opt/keycloak/providers/*.jar

# return to the keycloak user
USER keycloak

# Setting the build parameter for the database:
ENV KC_DB=oracle
#ENV KC_DB=${KC_DB}
# Add all other build parameters needed, for example enable health and metrics:
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true
ENV KC_HTTP_RELATIVE_PATH=/auth
ENV KC_HTTP_MANAGEMENT_RELATIVE_PATH=/auth
ENV KC_TRANSACTION_XA_ENABLED=false

#ENV KC_HTTP_MANAGEMENT_PORT=9000
# Only testing
#ENV KC_LEGACY_OBSERVABILITY_INTERFACE=true
#
#ENV JAVA_OPTS='-javaagent:/opt/keycloak/opentelemetry/opentelemetry-javaagent.jar'
#Add opentelemetry
#COPY --chown=keycloak:keycloak opentelemetry/opentelemetry-javaagent.jar /opt/keycloak/opentelemetry/

ENV KC_FEATURES="preview,hostname:v2,token-exchange"
#ENV KC_FEATURES="authorization,account,account-api,admin-fine-grained-authz,admin,docker,impersonation,token-exchange,client-policies,declarative-ui,dynamic-scopes,preview"
#[account, account-api, admin, admin-api, admin-fine-grained-authz, authorization, cache-embedded-remote-store, ciba, client-policies, client-secret-rotation, client-types, clusterless, declarative-ui, device-flow, docker, dpop, dynamic-scopes, fips, impersonation, kerberos, login, multi-site, oid4vc-vci, opentelemetry, organization, par, passkeys, persistent-user-sessions, preview, recovery-codes, scripts, step-up-authentication, token-exchange, transient-users, update-email, web-authn]
# ENV KC_CACHE=local

# To be able to use the image with the {project_name} Operator, it needs to be optimized, which requires {project_name}'s build step:
RUN /opt/keycloak/bin/kc.sh build -v
RUN /opt/keycloak/bin/kc.sh show-config

# ====
# Step 3/3: Final image
# ====
FROM registry.redhat.io/rhbk/keycloak-rhel9:${RHBK_IMAGE_VERSION}
COPY --from=builder-keycloak-image /opt/keycloak/ /opt/keycloak/

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
#ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start"]

# EOF